@startuml
actor TrafficManager as admin

participant ":ImportShipsUI" as UI
participant ":ImportShips\nController" as CTRL
participant ":FileReader" as FR

activate admin
admin -> UI: Starts importing ships from a text file
activate UI
UI --> admin: Asks for path to file
deactivate UI
admin -> UI: Introduces path


deactivate admin

@enduml