@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TF
participant ":UI" as UI
participant ":shipPairController" as CTR
participant ":Company" as COMP
participant ":Ship" as SP
participant ":Store" as STR
participant ":BST" as BST

TF->UI : Request ships with close/departure coordinates \nand different Travelled Distance
activate UI
UI->CTR : shipDto=getShipsClose()
activate CTR
CTR->COMP : shipStore=getShipStore()
activate COMP
deactivate COMP
CTR->STR : shipsClose=getShipsClose()
activate STR
deactivate STR
CTR->BST : shipsCloseDto= find(shipsClose)
activate BST
deactivate BST
CTR->UI : ok
deactivate CTR
UI->TF : ok
deactivate UI




@enduml