@startuml
'https://plantuml.com/sequence-diagram

top to bottom direction

company"1" --- "1..*"truck : > owns
company"1" --- "1..*"ship : > owns
company"1" --- "1..*"shipCrew : > owns
company"1" -- "1"warehouse : > has
company"1" -- "1"client : > has
company"1" -- "1"port : > has
ship"1" -- "1..*" container:> transports
ship"1" -- "1"location:> has a
container"1" -- "1"dimension :> has a
container"1" -- "1"coordinates:>has
truck"1" -- "1"container:> transports
warehouse"1" --"1"location :> has
warehouse"1" --"1..*"cargoManifest :> receives
port"1" --"1"location :> has
port"1" -- "1..*"cargoManifest :> receives
shipCrew"1" -- "1"ship :> works
cargoManifest"1" -- "1"shipCrew :> delivered

class company{
}

class dimension{
-width
-height
-length
}

class shipCrew{
}

class container{
-identification
-payload
-tare
-gross
-isoCode
-temperature
-refrigeration
}

class truck{
}

class ship{
-mmsi
-name
-imoId
-nrGenerators
-generatorPo
-callSign
-vesselType
-length
-width
-capacity
-draft
-baseDateTime
-sog
-cog
-heading
-position
-transceiverClass
}

class coordinates{
-xValue
-yValue
-zValue
}

class location{
-latitude
-longitude
}

class port{
-id
-name
-continent
-country
}

class warehouse{
-id
-name
-continent
-country
}

class cargoManifest{
-id
-containerPosition
-containerGrossWeight
}


@enduml

